Rewrite to parallelize and revise heuristics

diff --git a/urssh b/urssh
--- a/urssh
+++ b/urssh
@@ -1,42 +1,90 @@
 #!/usr/bin/env bash
 
-username=jkottas
-
-file=/tmp/urssh
+username="$USER"
+format="%u@%m"
 
 verbose=false
-list=false
-count=false
+quiet=false
+action=ssh
 fast=true
 each=false
 
 for arg; do
     case "$arg" in
-        (-v)
+        (--verbose|-v)
             verbose=true
+            quiet=false
+            ;;
+
+        (--quiet|-q)
+            verbose=false
+            quiet=true
             ;;
 
         (--list|-l)
-            list=true
+            action=list
+            ;;
+
+        (--ssh|-s)
+            action=ssh
             ;;
 
         (--fast|-f)
             fast=true
             ;;
 
-        (--each)
+        (--each|-e)
             each=true
             ;;
 
         (--all|-a)
             fast=false
             ;;
+
+        (--user=*|--username=*)
+            username="$(awk -F= '{print $2}' <<< "$arg")"
+            ;;
+
+        (--format=*)
+            format="$(awk -F= '{print $2}' <<< "$arg")"
+            ;;
+
+        (*)
+            echo "error: unrecognized argument: $arg" >&2
+            exit 1
+            ;;
     esac
 done
 
-if ! $list; then
-    count=true
-fi
+sub()
+{
+    echo 's/\([^%]\|^\)'"$1"'/\1'"$2"'/g'
+}
+
+format_machine()
+{
+    local user machine_short machine_long
+
+    user="$(awk -F@ '{print $1}' <<< "$1")"
+    machine_long="$(awk -F@ '{print $2}' <<< "$1")"
+    machine_short="$(awk -F. '{print $1}' <<< "$machine_long")"
+
+    sed "
+        $(sub "%m" "$machine_short")
+        $(sub "%M" "$machine_long")
+        $(sub "%u" "$user")
+        s/%%/%/g
+    " <<< "$format"
+}
+
+format_machines()
+{
+    local machine
+
+    while read -r machine; do
+        format_machine "$machine"
+    done
+}
 
 get_machines()
 {
@@ -53,49 +101,109 @@ get_machines()
     fi
 }
 
-user_cmd="users | tr ' ' '\n' | sort | uniq | tr '\n' ' '"
-count_user_cmd="users | tr ' ' '\n' | sort | uniq | wc -l"
-count_proc_cmd="grep -F processor /proc/cpuinfo | wc -l"
-
-scale=20
-
-get_machine_users()
+get_formated_machines()
 {
-    ! $verbose || echo "sshing into machine '$1'" >&2
-    users="$(ssh "$1" "$user_cmd" 2>/dev/null)"
-    echo "$users"
+    get_machines | format_machines
 }
 
-get_machine_users_count()
+get_users()
 {
-    ! $verbose || echo "sshing into machine '$1'" >&2
-    user_count="$(ssh "$1" "$count_user_cmd" 2>/dev/null)"
-    ! $verbose || echo "machine '$1' has $user_count users" >&2
-    echo "$user_count"
+    users | tr ' ' '\n'
 }
 
-get_machine_proc_count()
+uniq_users()
 {
-    ! $verbose || echo "sshing into $1" >&2
-    procs="$(ssh "$1" "$count_proc_cmd" 2>/dev/null)"
-    ! $verbose || echo "machine '$1' has $procs processors" >&2
-    echo "$procs"
+    get_users | sort | uniq
 }
 
-get_machine_rating()
+n_users()
 {
-    cmd="echo \"scale=$scale; \$($count_user_cmd) / \$($count_proc_cmd)\" | bc"
-    ! $verbose || echo "running '$cmd' on machine '$1'" >&2
-    rating="$(ssh "$1" "$cmd" 2>/dev/null)"
+    get_users | wc -l
+}
 
-    ! $verbose || echo "machine '$1' has rating $rating" >&2
-    echo "$rating"
+n_uniq_users()
+{
+    uniq_users | wc -l
+}
+
+meminfo()
+{
+    awk -F':? +' "\$1 == \"$1\" {print \$2}" /proc/meminfo
+}
+
+mem_avail()
+{
+    meminfo MemAvailable
+}
+
+cpuinfo()
+{
+    lscpu | awk -F': +' "\$1 == \"$1\" {print \$2}"
+}
+
+n_cpus()
+{
+    cpuinfo "CPU(s)"
+}
+
+load_avgs()
+{
+    uptime | awk -F'[,:] ' '{print $NF, $(NF - 1), $(NF - 2)}'
+}
+
+load_avgs_avg()
+{
+    bc -l <<< "($(load_avgs | sed 's/ /+/g')) / 3"
+}
+
+get_rating()
+{
+    bc -l <<EOF
+n_uniq_users  = $(n_uniq_users)
+load_avgs_avg = $(load_avgs_avg)
+n_cpus        = $(n_cpus)
+mem_avail     = $(mem_avail)
+
+(n_uniq_users + 1) * (load_avgs_avg + 1) / (n_cpus * \
+   (mem_avail / 1048576))
+EOF
+}
+
+func_cat()
+{
+    local str=
+
+    for arg; do
+        str="$(cat <(echo "$str") <(type "$arg" | tail -n +2))"
+    done
+
+    echo "$str"
+}
+
+funcs="$(func_cat get_users uniq_users n_users n_uniq_users meminfo mem_avail \
+    cpuinfo n_cpus load_avgs load_avgs_avg get_rating)"
+
+do_ssh()
+{
+    machine="$1"
+
+    if ! ssh "$machine" true 2>/dev/null; then
+        $quiet || echo "Unable to ssh into $(format_machine "$machine")" >&2
+        return 1
+    fi
+
+    cmd="$(cat <(echo "$funcs") <(echo "$2"))"
+
+    ! $verbose || echo "MACHINE: $machine" >&2
+    ! $verbose || echo "COMMAND: $2" >&2
+
+    ssh "$machine" "$cmd"
 }
 
 wait_for_children()
 {
     if $fast; then
-        sleep 2
+        sleep 5
         pkill -P $$
     else
         wait
@@ -104,46 +212,48 @@ wait_for_children()
 
 machines="$(get_machines)"
 
-if $each; then
-    for machine in $machines; do
-        ssh "$machine"
-    done
-elif $count; then
-    >"$file"
+case "$action" in
+    (ssh)
+        if $each; then
+            for machine in $machines; do
+                $quiet || echo \
+                    "sshing into $(format_machine "$machine")"
+                do_ssh "$machine" ". ~/.bashrc"
+            done
+        else
+            tmpdir="$(mktemp -d)"
+            for machine in $machines; do
+                do_ssh "$machine" get_rating >"$tmpdir/$machine" &
+            done
+            wait_for_children
+            min=1000
+            minmachine=
+            for machine in $machines; do
+                rating="$(cat "$tmpdir/$machine")"
+                if [ -n "$rating" ] && [ "$(bc <<< "$rating < $min")" = 1 ]
+                then
+                    min="$rating"
+                    minmachine="$machine"
+                fi
+            done
+            exec ssh "$minmachine"
+        fi
+        ;;
 
-    for machine in $machines; do
-        get_machine_rating "$machine"
-    done >"$file"
+    (list)
+        tmpdir="$(mktemp -d)"
+        for machine in $machines; do
+            do_ssh "$machine" 'echo $(n_uniq_users) $(uniq_users)' \
+                >"$tmpdir/$machine" &
+        done
+        wait_for_children
+        for machine in $machines; do
+            info="$(cat "$tmpdir/$machine")"
+            [ -n "$info" ] && echo "$(format_machine "$machine") $info"
+        done
+        ;;
 
-    machine="$(echo "$machines" | sed -n "$(awk '
-    NR == 1 {
-        min = $0;
-        min_line = 1;
-    }
-
-    NR > 1 {
-        if ($0 < min) {
-            min = $0;
-            min_line = NR;
-        }
-    }
-
-    END {
-        print min_line;
-    }
-    ' "$file")p")"
-
-    ! $verbose || echo "sshing into machine '$machine'" >&2
-
-    ssh "$machine"
-elif $list; then
-    # TODO - optimize this, since it's unnecessarily sshing to each machine
-    # twice
-    for machine in $machines; do
-        (echo "$machine $(get_machine_users_count \
-            "$machine") $(get_machine_users "$machine")") &
-    done
-    wait_for_children
-else
-    echo "error!" >&2
-fi
+    (*)
+        echo 'error: unknown action' >&2
+        exit 1
+esac
